### ISSUE TITLE
[Feature Request]:Can I get the server side code for light tube,piped or invidious.

### ISSUE THREAD

**Issue by Abhinayckrs** [lighttube-org/LightTube#147]
### Description

Currently, our college network restricts access to YouTube via the Sophos firewall, blocking popular alternative video streaming platforms like Invidious, Piped, and Light Tube. Despite attempts to bypass this restriction using local instances on Amazon EC2, access remains blocked.
![inv1](https://github.com/lighttube-org/LightTube/assets/123803356/3f574c5a-a77e-4fe5-9fe3-1cd358a1c4f8)
![inv2](https://github.com/lighttube-org/LightTube/assets/123803356/ae108822-cc18-41d8-a885-e0c303ad360e)

**Comment by InFTord** [comment]
just... read the source code? it's right here???????????????
