### ISSUE TITLE
[Bug] "Couldn't render: ExceptionRenderer" 

### ISSUE THREAD

**Issue by cursedmantra** [lighttube-org/LightTube#151]
### Describe the bug

Comments in any video do not work and only display the error "Couldn't render: ExceptionRenderer" 
![image](https://github.com/lighttube-org/LightTube/assets/135048044/472e7c5b-8c70-4073-9d0c-d1b2c543d0d5)

**Comment by dsezerpy** [comment]
does this also occur in tube.kuylar.dev or is it in another instance?

**Comment by kuylar** [comment]
Occurs everywhere because YouTube changed how comments are rendered. InnerTube 2.0.0-rc1 fixes this but it's not ready yet. Same applies to #150, but for channel headers
