### ISSUE TITLE
[Bug] Video Unavailable

### ISSUE THREAD

**Issue by Loading617** [lighttube-org/LightTube#176]
### Describe the bug

When I keep going to a video, it keeps saying Video Unavailable

**Comment by epman100** [comment]
confirmed that the "video unavailable" problem occurs on my end, using tube.kuylar.dev instance

**Comment by Loading617** [comment]
thanks man!!

**Comment by epman100** [comment]
looks like all videos on tube.instellate.xyz have also stopped working earlier this November 2024.
so now all LightTube instances no longer work.  time for me to temporarily abandon LightTube until such instances get updated to work with the recent youtube changes.
